// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adkaxjxtvlsdcvkvewxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFka2F4anh0dmxzZGN2a3Zld3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTUzMTEsImV4cCI6MjA3MDIzMTMxMX0.A5UhNbWdjjKaBW-9S6nXdd4NK9wdmOSJ3W6evzvQ_ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});